version: 1.0.{build}
build:
  project: source/DasBlog All.sln
  verbosity: minimal
test: off
notifications:
  - provider: Email
    to:
      - scott@hanselman.com
  - provider: GitHubPullRequest
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
